### ISSUE TITLE
CakePHP 2.4 Support

### ISSUE THREAD

**Issue by lucasbento** [andufratu/jwt-auth#1]
I'm trying to use this plugin with CakePHP 2.4, is it possible to do so?

Thank you.

**Comment by andufratu** [comment]
Hi, I think it should be compatible, yes. In theory CakePHP 2.6+ is backwards compatible with 2.4, as far as the API is concerned. I tried running the tests with CakePHP 2.4 installed and they passed, although I had to manually include some files instead of depending on composer's autoload. If you use composer you'll probably have to fork the repo and change the required version for cakephp to be ^2.4 because it currently is ^2.6 since those are the versions I've run the plugin with in production.
I hope it works for you.
